/*
 * buildopts.h 
 * Automatically generated
 */

#define LOADABLE_MODULES 1
#define BUILD_NATIVE 1
#define AST_MODULE_CHAN_LOCAL 1
#define AST_MODULE_APP_VOICEMAIL 1
#define AST_MODULE_RES_MONITOR 1
#define AST_MODULE_RES_AGI 1
#define AST_MODULE_RES_ADSI 1
#define AST_MODULE_RES_SMDI 1
#define AST_MODULE_RES_CRYPTO 1
#define AST_MODULE_G711_NEW_ALGORITHM 1
#define AST_BUILDOPT_SUM "ff2af156f1bd3f028acd55fb53211ae9"
#define AST_BUILDOPTS "LOADABLE_MODULES, BUILD_NATIVE"
